# Generated by Code Genesis (C → Python Transpiler)
# Team Striver | Compiler Design TCS-601

class Pointer:
    def __init__(self, value, is_ref=False):
        if is_ref: self.store = value
        else: self.store = [value]
    @property
    def val(self): return self.store[0]
    @val.setter
    def val(self, v): self.store[0] = v

def factorial(n):
    if (n <= 1):
        return 1
    return (n * factorial((n - 1)))

def main():
    i = 1
    while (i <= 5):
        f = factorial(i)
        print(i)
        print(f)
        i = (i + 1)
    return 0


if __name__ == '__main__':
    main()